services:
  backend:
    build: .
    command:
      - gunicorn
      - --workers
      - "3"
      - --bind
      - "0.0.0.0:8000"
      - config.wsgi:application
    env_file:
      - ./.env
    networks:
      - live
    volumes:
      - ./static:/app/static




  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static:/app/static
    ports:
      - "80:80"
    networks:
      - live
    depends_on:
      - backend






networks:
  live:
    driver: bridge
