# Generated by Django 5.1.1 on 2024-10-01 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_remove_book_expired_at_remove_genre_expired_at_rate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='Book',
            new_name='book',
        ),
    ]
